networks:
  mutex_network:
    driver: bridge  

services:
  mutex-node-1:
    networks:
      - mutex_network
    build:
      context: .
      args:
        BASE_PORT: 5000
        BASE_HOSTNAME: mutex-node
        NUM_NODES: 4
    environment:
      - BASE_PORT=5000
      - BASE_HOSTNAME=mutex-node
      - NUM_NODES=4
      - NODE_ID=0  
    logging:
      driver: "json-file"
  
  mutex-node-2:
    networks:
      - mutex_network
    build:
      context: .
      args:
        BASE_PORT: 5000
        BASE_HOSTNAME: mutex-node
        NUM_NODES: 4
    environment:
      - BASE_PORT=5000
      - BASE_HOSTNAME=mutex-node
      - NUM_NODES=4
      - NODE_ID=1 
  
  mutex-node-3:
    networks:
      - mutex_network
    build:
      context: .
      args:
        BASE_PORT: 5000
        BASE_HOSTNAME: mutex-node
        NUM_NODES: 4
    environment:
      - BASE_PORT=5000
      - BASE_HOSTNAME=mutex-node
      - NUM_NODES=4
      - NODE_ID=2 

  mutex-node-4:
    networks:
      - mutex_network
    build:
      context: .
      args:
        BASE_PORT: 5000
        BASE_HOSTNAME: mutex-node
        NUM_NODES: 4
    environment:
      - BASE_PORT=5000
      - BASE_HOSTNAME=mutex-node
      - NUM_NODES=4
      - NODE_ID=3
